### ISSUE TITLE
No 3rd party code can go in our repo.

### ISSUE THREAD

**Issue by ptressel** [elcano/SelfDrive#14]
Do not put any 3rd party code, including Arduino libraries, into our repositories.  I will remove them asap.  It is not legal according to their licenses.  In addition, we should not have code not written by us, regardless of license.

**Comment by ptressel** [comment]
For now, I will just git rm the illegal libraries.  That will not take them out as they will be in the history.  To remove them entirely, the entire repo will have to be deleted, or rewritten to remove the illegal code.

In any case, be aware that this repo is likely deprecated.  I'll be migrating live code to the main repo.  The main repo has the correct layout for use with the Arduino IDE, where this repo cannot be used without moving the code.

**Comment by TylerFolsom** [comment]
Repo is depricated
